name: twinlitenetplus_nano
version: default
encoder:
  in_channels: 3
  level_0_ch: 4
  level_1_ch: 8
  level_2_ch: 16
  level_3_ch: 32
  level_4_ch: 64
  out_channels: 16
  p: 1
  q: 1
caam:
  in_channels: 16
  num_classes: 16
  out_channels: 8
decoder:
  in_channels: 8
  level_0_ch: 4
  level_1_ch: 8
  out_channels: 4
