experiment_name: "single_litenet_aida_large"
data_root: "/home/paolopertino/Desktop/Datasets/BDD100k"
root_log_dir: /home/paolopertino/Desktop/SingleLiteNetPlus/weightslab_logs
device: "cuda"
training_steps_to_do: 175000
image_size: 640
num_classes: 6
ignore_index: 255
eval_full_to_train_steps_ratio: 100
optimizer:
  lr: 1e-3
data:
  train_loader:
    batch_size: 4
    num_workers: 0
    shuffle: false
  test_loader:
    batch_size: 4
    num_workers: 0

model:
  name: "large"
  encoder:
    level_0_ch: 32
    level_1_ch: 64
    level_2_ch: 128
    level_3_ch: 256
    level_4_ch: 512
    out_channels: 128
    p: 5
    q: 7
  caam:
    in_channels: 128
    out_channels: 64
  decoder:
    in_channels: 64
    level_0_ch: 32
    level_1_ch: 8
