experiment_name: bdd_segmentation
data_root: /Users/marcgraybx/graybox/development/data/BDD100k_reduced
training_steps_to_do: 2000
eval_full_to_train_steps_ratio: 50
num_classes: 6
image_size: 128
device: mps