degrees: 10 #Rotation
translate: 0.1 #Translate
scale: 0.5 #Scale
shear: 0.0 #Shear
hgain: 0.015 #Hgain
sgain: 0.7 #Sgain
vgain: 0.4 #Vgain
width_crop: 960 #Width for RandomCrop
height_crop: 540 #Height for RandomCrop
resize_largest_side: 640 # Resize the largest size (in our case the width) to this dim and randomly pad the other

prob_perspective: 0.5
prob_hsv: 0.5
prob_flip: 0.5
prob_bilateral: 0.1
prob_gaussian: 0.1
prob_crop: 0.1
prob_downscale: 0. # By Default, the image is not downscaled.