device: cpu
root_log_dir: "/tmp/weightslab_mnist"
tqdm_display: true
skip_loading: true

experiment_name: Exp_CNN_Test

training_steps_to_do: 1000000
eval_full_to_train_steps_ratio: 100
experiment_dump_to_train_steps_ratio: 670000
skip_checkpoint_load: false

# start training immediately
is_training: true

data:
  train_loader:
    train_shuffle: true
    batch_size: 64
  test_loader:
    test_shuffle: false
    batch_size: 64
    drop_last: false

optimizer:
  lr: 0.01
